### ISSUE TITLE
documentation improvemnt for algorithms in petgraph::algo::isomorphism

### ISSUE THREAD

**Issue by raphaelahrens** [petgraph/petgraph#600]
### Summary

The documentation for all algorithms in petgraph::algo::[isomorphism](https://docs.rs/petgraph/latest/petgraph/algo/isomorphism/index.html#) is vague in regards to multigraphs.

### Motivation

For all functions there is the statement "The graphs should not be multigraphs.", without an explanation of what that means.
I looked into the paper for VF2 and was able to find that .

>From the analysis of the table, it appears that Nauty is more
>convenient on randomly connected graphs that exhibit no regular
>structure, especially when the edge density becomes high. This kind
>of graph, anyway, does not adequately represent the graph
>structures found in many applications, where the graphs often
>show some form of regularity. On the other hand, for graphs with a
>more regular structure, VF2 is more efficient, especially for large
>graph sizes

But to be honest this does not say much either, there is no statement on how much faster the algorithm was, only that one algorithm was faster than another.

### Details

I would propose to remove the sentence "The graphs should not be multigraphs" and add a more detailed explanation.
From the paper I assume the algorithm does work with multigraphs, but will not perform well.
So the new statement could be something like.
```
Note: While it is possible to use the algorithm with [multigraphs](https://en.wikipedia.org/wiki/Multigraph), it might perform poorly.
```
Maybe some guidance on how to trigger the worst case for the algorithm.

**Comment by raphaelahrens** [comment]
Hey, sorry to push on this issue, but is this going to be ignored or has it just been forgotten?

My solution was to implement my own copy from ["Algorithms on trees and graphs" ](https://archive.org/details/algorithmsontree0000vali/mode/2up), but I would still like to know if I could use the provided algorithm.

**Comment by bluss** [comment]
The comment about multigraphs means that our implementation does not work with multigraphs (unless it has changed in a way that I don't remember).

**Comment by raphaelahrens** [comment]
Thank you for the reply.
As soon as I find the time I would like to change the wording of the docs to properly state that these algorithms do not work with multigraphs.

Would you be interested in an algorithm which supports multigraphs or should I create a separate crate, if I want to publish my own sollution?

**Comment by bluss** [comment]
@raphaelahrens my advice, review other VF2 related algo work in open PRs and issues, get in touch with those authors, ask @indietyp (probably blocked by 0.7 work) and I am not available to design or review any significant algo work at the moment

**Comment by OwenTrokeBillard** [comment]
I implemented VF2 for petgraph graphs in another crate: https://github.com/OwenTrokeBillard/vf2. It supports disconnected graphs (multigraphs).

**Comment by matth2k** [comment]
Hi all. The linked PR #824 does not solve the spirit of the issue. 

> For all functions there is the statement "The graphs should not be multigraphs.", without an explanation of what that means.

This still reflects the state of the docs, so I am unsure which avenue will be best for my problem. Can the limitation please be explained in the docs? Is @OwenTrokeBillard 's crate still the best way to go for isomorphism problems on multigraphs? Thanks

**Comment by RaoulLuque** [comment]
Hi there, sry for the late reply. I am unfortunately not capable to answer that question I'm afraid. I have not had the time to accustom myself with the Isomorphism implementations of `petgraph`. I suspect that the implementation is just plainly not compatible with multigraphs.

However, I am confused by @OwenTrokeBillard 's answer since he states that it supports disconnected (multigraphs). Which to me are somewhat unrelated concepts. Furthermore, by a quick google search it seems like the original VF2 algorithm does indeed not support multigraphs. However, with slight adaptions they might have still made that work nonetheless. So, for now `petgraph` doesn't support multigraphs for this scenario, however I am unsure whether @OwenTrokeBillard implementation actually adresses this by his answer 🤔 

In any case, I am open to expanding/revamping the capabilities of `petgraph` with respect to this and am myself interested in learning more about the VF2(++) algorithm. I hope this clears it somewhat, even if it may not be satisfactory 🦕

**Comment by OwenTrokeBillard** [comment]
You are welcome to take `vf2` and fold it into petgraph. Let me know, I'll transfer ownership. Add me as a contributor.

My memory on multi-graphs are hazy. I recall `vf2` supports disconnected graphs (multiple disjoint subgraphs) but unsure about parallel edges.
